language: node_js

node_js:
  - "lts/*"
  - "node"

os:
  - linux
  - windows

cache:
  directories:
    - "node_modules"

before_install:
  - if [[ "$TRAVIS_OS_NAME" != 'windows' ]]; then npm run docker:start; fi

install:
  - npm install

script:
  - npm run compile
  - npm run lint
  - npm run test:unit
  - if [[ "$TRAVIS_OS_NAME" != 'windows' ]]; then npm run test:int; fi

