[profile.default]
src = "contracts"
test = "contracts/test"
script = "contracts/script"
libs = ["solidity-lib"]
gas_reports = ["EtherSwap", "ERC20Swap", "Router"]
solc_version = "0.8.33"

[profile.release]
optimizer = true
optimizer_runs = 10_000_000

[profile.release-rsk]
optimizer = true
optimizer_runs = 10_000_000
evm_version = "istanbul"

[fuzz]
runs = 8192

[fmt]
ignore = ["solidity-lib/**/*"]

[lint]
ignore = ["solidity-lib/**/*"]
