/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { Contract, ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import { ContractEvent, Callback, TransactionObject, BlockType } from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class ERC20Swap extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  clone(): ERC20Swap;
  methods: {
    create(
      _preimageHash: string | number[],
      _amount: number | string,
      _erc20Token: string,
      _claimAddress: string,
      _timelock: number | string
    ): TransactionObject<void>;

    claim(
      _preimageHash: string | number[],
      _preimage: string | number[]
    ): TransactionObject<void>;

    refund(_preimageHash: string | number[]): TransactionObject<void>;

    getSwapInfo(
      _preimageHash: string | number[]
    ): TransactionObject<{
      amount: string;
      erc20Token: string;
      claimAddress: string;
      refundAddress: string;
      timelock: string;
      pending: boolean;
      0: string;
      1: string;
      2: string;
      3: string;
      4: string;
      5: boolean;
    }>;
  };
  events: {
    Claim: ContractEvent<string>;
    Creation: ContractEvent<string>;
    Refund: ContractEvent<string>;
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
