version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout:
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: compile
          command: npm run compile
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm run test
