version: 2
jobs:
  build:
    machine:
      enabled: true
      image: circleci/classic:edge
  
    steps:
      - checkout:

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run:
          name: Compile
          command: npm run compile

      - run:
          name: Lint
          command: npm run lint

      - run:
          name: Test
          command: npm run test
