import web3 from 'web3';

/**
 * Get a hex encoded Buffer from a string
 *
 * @returns a hex encoded Buffer
 */
export const getHexBuffer = (input: string) => {
  return Buffer.from(input, 'hex');
};

/**
 * Get a hex encoded string from a Buffer
 *
 * @returns a hex encoded string
 */
export const getHexString = (input: Buffer) => {
  return input.toString('hex');
};

/**
 * Get a byte array masked as string because that data type is
 * required by the types generated by typechain
 */
export const bufferToBytes = (input: Buffer) => {
  return web3.utils.hexToBytes(`0x${getHexString(input)}`) as any as string;
};

/**
 * Get a timestamp in the Ethereum format (like a UNIX timestamp but divided by 1000)
 */
export const getEthereumTimestamp = () => {
  return Math.floor(Date.now() / 1000);
};
